---
# Main tasks file for the role
- name: Install chrony package
  ansible.builtin.package:
    name: chrony
    state: present

- name: Configure chrony
  ansible.builtin.template:
    src: chrony.conf.j2
    dest: /etc/chrony.conf
    owner: root
    group: root
    mode: '0644'
  notify: restart chrony

- name: Ensure chrony service is enabled and started
  ansible.builtin.service:
    name: "{{ chrony_service_name }}"
    state: started
    enabled: true
