---
dependency:
  name: galaxy
driver:
  name: docker
platforms:
  - name: ubuntu-instance
    image: geerlingguy/docker-ubuntu2204-ansible:latest
    hostname: ubuntu
    privileged: True
    pre_build_image: True
    override_command: False
    cgroupns_mode: host
    systemd: always
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:rw
    capabilities:
      - SYS_ADMIN
    tmpfs:
      - /tmp
      - /run
      - /run/lock

  # - name: rocky-instance
  #   image: geerlingguy/docker-rockylinux9-ansible:latest
  #   hostname: ubuntu
  #   privileged: True
  #   pre_build_image: True
  #   override_command: False
  #   cgroupns_mode: host
  #   systemd: always
  #   volumes:
  #     - /sys/fs/cgroup:/sys/fs/cgroup:rw
  #   capabilities:
  #     - SYS_ADMIN
  #   tmpfs:
  #     - /tmp
  #     - /run
  #     - /run/lock

provisioner:
  name: ansible
  playbooks:
    prepare: prepare.yml
    converge: ${MOLECULE_PLAYBOOK:-converge.yml}
    verify: verify.yml
  config_options:
    defaults:
      interpreter_python: auto_silent
    ssh_connection:
      pipelining: true
  env:
    ANSIBLE_FORCE_COLOR: "true"
    ANSIBLE_FILTER_PLUGINS: "${ANSIBLE_FILTER_PLUGINS:-./plugins/filter}"
    # ANSIBLE_ROLES_PATH: ../../

verifier:
  name: ansible
  options:
    verbose: true
