---
- name: Verify
  hosts: all
  gather_facts: true
  tasks:
    - name: Set service name based on OS family
      ansible.builtin.set_fact:
        chrony_service_name: "{{ 'chronyd' if ansible_os_family == 'RedHat' else 'chrony' }}"

    - name: Check if chrony package is installed
      ansible.builtin.package:
        name: chrony
        state: present
      check_mode: true

    - name: Check if chrony service is running
      ansible.builtin.service:
        name: "{{ chrony_service_name }}"
        state: started
      check_mode: true

    - name: Check if chrony service is enabled
      ansible.builtin.service:
        name: "{{ chrony_service_name }}"
        enabled: true
      check_mode: true

    - name: Check chrony configuration
      ansible.builtin.shell: |
        grep -q "pool {{ chrony_ntp_server }}" /etc/chrony.conf
      changed_when: false
      check_mode: true

    - name: Check chrony synchronization
      ansible.builtin.shell: |
        chronyc tracking
      changed_when: false
      check_mode: true
