---
- name: Verify
  hosts: all
  gather_facts: true
  vars_files:
    - ../../defaults/main.yml
  # vars:
  #   chrony_ntp_server: "0.pl.pool.ntp.org"
  #   chrony_service_name: "chrony"
  tasks:
    - name: Check if chrony package is installed
      ansible.builtin.package:
        name: chrony
        state: present
      check_mode: true

    - name: Check if chrony service is running
      ansible.builtin.service:
        name: "{{ chrony_service_name }}"
        state: started
      check_mode: true

    - name: Check if chrony service is enabled
      ansible.builtin.service:
        name: "{{ chrony_service_name }}"
        enabled: true
      check_mode: true

    - name: Check chrony configuration
      ansible.builtin.shell: |
        grep -q "pool {{ chrony_ntp_server }}" /etc/chrony.conf
      changed_when: false
      check_mode: true

    - name: Check chrony synchronization
      ansible.builtin.shell: |
        chronyc tracking
      changed_when: false
      check_mode: true
