name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
      - "feature/*"
      - "release/*"
      - "bugfix/*"
      - "hotfix/*"

jobs:
  lint:
    name: Lint code
    runs-on: ubuntu-latest
    steps:
      - name: Check out the codebase
        uses: actions/checkout@v4
      - name: Set up Python 3
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'
      - name: Install dependencies
        run: |
          pip3 install yamllint
      - name: Lint code
        run: |
          yamllint .
  molecule:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 4
      matrix:
        distro:
          - ubuntu2004
          - ubuntu2204
        python-version:
          - 3.12
    steps:
      - name: Check out the codebase
        uses: actions/checkout@v4

      - name: Set up Python 3
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          pip3 install ansible molecule molecule-plugins[docker] \
            docker testinfra

      - name: Run molecule test
        run: molecule test
        env:
          PY_COLORS: '1'
          ANSIBLE_FORCE_COLOR: '1'
          MOLECULE_DISTRO: ${{ matrix.distro }}
